theme='emhyr'

editor.scrolloff=8

editor.continue-comments=false
editor.gutters=[]
editor.auto-completion=false
editor.path-completion=false
editor.auto-format=false
editor.auto-info=false
editor.true-color=true
editor.rulers=[81]
editor.insert-final-newline=false

editor.statusline.left=['mode','spinner','file-name']
editor.statusline.right=['selections','position']

editor.lsp.enable=false

editor.cursor-shape.normal='block'
editor.cursor-shape.insert='bar'
editor.cursor-shape.select='block'

editor.file-picker.hidden=false
editor.file-picker.parents=false
editor.file-picker.ignore=false
editor.file-picker.git-ignore=false
editor.file-picker.git-global=false
editor.file-picker.git-exclude=false

editor.auto-pairs=false

editor.search.smart-case=false