'string'            ='cyan'
'constant.numeric'  ='cyan'
'constant.character'='cyan'
'keyword'           ='magenta'
'operator'          ='magenta'
'punctuation'       ='magenta'
#'comment'           ='gray'
'comment'           ='red'

'ui.selection' ={modifiers=['reversed']}
'ui.statusline'={modifiers=['reversed']}

'ui.bufferline.active'={bg='magenta'}
'ui.menu.selected'    ={bg='magenta'}

'error'  ='red'
'warning'='yellow'
'info'   ='green'

'diagnostic'={underline={style='line'}}
